/**
 * Sovereign Artisanal Sourcing & Doré Refinery Bridge Service
 *
 * Implements Black Paper Strategy #1 & Q144/Q145:
 * - Formalizes artisanal gold miners (orpailleurs) across Mali, Burkina Faso, and Niger.
 * - Sourcing at state buying counters with handheld XRF spectrometry testing.
 * - Instant payout settlement in AngelCoin at 95%+ of global spot price.
 * - Anti-tamper assayer hardware verification (Premortem H-002).
 * - Strict Reserve Purity Boundary: raw doré ore is held in transit and NEVER enters
 *   the circulating Proof-of-Reserves Merkle tree until refined to >= 99.50% bullion.
 */

import { prisma } from "@/lib/db";
import { getCommoditySpotPrices } from "./commodity-oracle";
import { generateLivePoR } from "./por-service";
import { canonicalJson } from "@/lib/receipt/canonical";
import { verify } from "@noble/ed25519";
import { hexToBytes, utf8ToBytes } from "@noble/hashes/utils.js";

const COMMITMENT_RE = /^[0-9a-f]{64}$/i;
const MIN_REFINED_FINENESS = 0.9950; // London Good Delivery minimum purity (99.50%)

export interface PayoutCalculation {
  grossGrams: number;
  fineness: number;
  fineGrams: number;
  spotPriceUsd: number;
  payoutRatePercent: number;
  payoutUsd: number;
  payoutAngel: number;
}

export interface ProcessIntakeInput {
  receiptNumber: string;
  stationCode: string;
  minerCommitment: string;
  grossWeightGrams: number;
  assayedFineness: number;
  spectrometerSignature: string;
  payoutRatePercent?: number;
}

export interface BridgeDoreInput {
  receiptNumbers: string[];
  targetBatchNumber: string;
  vaultId: string;
  custodianName: string;
  locationCity: string;
  locationCountry: string;
  barSerials: string[];
  refinedGrossGrams: number;
  refinedFineness: number;
}

/**
 * Calculates artisanal miner payout at statutory spot rate (default 95%).
 */
export function calculateArtisanalPayout(
  grossGrams: number,
  fineness: number,
  spotPriceUsd: number,
  payoutRatePercent = 95.0
): PayoutCalculation {
  if (!Number.isFinite(grossGrams) || grossGrams <= 0) {
    throw new Error("grossGrams must be a positive number");
  }
  if (!Number.isFinite(fineness) || fineness < 0.50 || fineness > 1.0) {
    throw new Error("assayed fineness must be between 0.5000 and 1.0000");
  }
  if (!Number.isFinite(spotPriceUsd) || spotPriceUsd <= 0) {
    throw new Error("spotPriceUsd must be positive");
  }

  const fineGrams = Number((grossGrams * fineness).toFixed(4));
  const payoutUsd = Number((fineGrams * spotPriceUsd * (payoutRatePercent / 100)).toFixed(2));
  const payoutAngel = Math.floor(payoutUsd / 5.0); // Canonical $5.00/ANGEL rate

  return {
    grossGrams: Number(grossGrams.toFixed(4)),
    fineness: Number(fineness.toFixed(4)),
    fineGrams,
    spotPriceUsd: Number(spotPriceUsd.toFixed(2)),
    payoutRatePercent,
    payoutUsd,
    payoutAngel,
  };
}

/**
 * Verifies the Ed25519 signature generated by the handheld XRF spectrometer.
 */
export async function verifySpectrometerSignature(
  publicKeyHex: string,
  signatureHex: string,
  payload: Record<string, unknown>
): Promise<boolean> {
  if (!publicKeyHex || !signatureHex) return false;
  try {
    const canonical = canonicalJson(payload);
    return await verify(
      hexToBytes(signatureHex),
      utf8ToBytes(canonical),
      hexToBytes(publicKeyHex)
    );
  } catch {
    return false;
  }
}

/**
 * Records verified raw doré intake at a field station and credits the miner's wallet.
 */
export async function processOreIntake(input: ProcessIntakeInput) {
  if (!COMMITMENT_RE.test(input.minerCommitment)) {
    throw new Error("Invalid miner commitment (expected 64-character hex)");
  }

  // 1. Commodity Oracle Freshness Gate
  const spotPrices = getCommoditySpotPrices();
  const gold = spotPrices.Au;
  if (!gold || gold.isStale) {
    throw new Error("Commodity spot oracle feed is stale; artisanal intake refused");
  }

  // 2. Buying Station Verification
  const station = await prisma.artisanalBuyingStation.findUnique({
    where: { stationCode: input.stationCode },
  });
  if (!station) {
    throw new Error(`Artisanal buying station '${input.stationCode}' not found`);
  }
  if (station.activeStatus !== "ACTIVE") {
    throw new Error(`Station '${input.stationCode}' is currently ${station.activeStatus}`);
  }

  // 3. Payout Calculation (95% spot)
  const payout = calculateArtisanalPayout(
    input.grossWeightGrams,
    input.assayedFineness,
    gold.priceUsd,
    input.payoutRatePercent ?? 95.0
  );

  if (payout.payoutAngel < 1) {
    throw new Error("Intake value is below the minimum settlement threshold of 1 ANGEL ($5.00 USD)");
  }

  // 4. Spectrometer Signature Canonical Payload
  const assayPayload = {
    assayed_fineness: payout.fineness,
    gross_weight_grams: payout.grossGrams,
    miner_commitment: input.minerCommitment.toLowerCase(),
    receipt_number: input.receiptNumber,
    station_code: input.stationCode,
  };

  // Verify hardware signature if in production
  if (process.env.NODE_ENV === "production") {
    const isValidSignature = await verifySpectrometerSignature(
      station.stationPublicKey,
      input.spectrometerSignature,
      assayPayload
    );
    if (!isValidSignature) {
      throw new Error("Invalid spectrometer hardware signature; intake rejected");
    }
  }

  // 5. Execute Atomic Intake Transaction
  const receipt = await prisma.$transaction(async (tx) => {
    // Credit miner's agent wallet with instant AngelCoin payout
    await tx.agentWallet.upsert({
      where: { subjectCommitment: input.minerCommitment.toLowerCase() },
      create: {
        subjectCommitment: input.minerCommitment.toLowerCase(),
        balance: payout.payoutAngel,
        earnedTotal: payout.payoutAngel,
        lastActivityAt: new Date(),
      },
      update: {
        balance: { increment: payout.payoutAngel },
        earnedTotal: { increment: payout.payoutAngel },
        lastActivityAt: new Date(),
      },
    });

    // Record the raw ore intake receipt
    const createdReceipt = await tx.oreIntakeReceipt.create({
      data: {
        receiptNumber: input.receiptNumber,
        stationId: station.id,
        stationCode: station.stationCode,
        minerCommitment: input.minerCommitment.toLowerCase(),
        grossWeightGrams: payout.grossGrams,
        assayedFineness: payout.fineness,
        fineGoldGrams: payout.fineGrams,
        spotPriceUsdPerGram: payout.spotPriceUsd,
        payoutRatePercent: payout.payoutRatePercent,
        payoutUsd: payout.payoutUsd,
        payoutAngel: payout.payoutAngel,
        spectrometerSignature: input.spectrometerSignature,
        status: "PURCHASED",
      },
    });

    // Update station operational totals
    await tx.artisanalBuyingStation.update({
      where: { id: station.id },
      data: {
        totalPurchasedGrams: { increment: payout.grossGrams },
        totalPaidAngel: { increment: payout.payoutAngel },
      },
    });

    return createdReceipt;
  });

  return {
    receipt,
    payout,
  };
}

/**
 * Bridges accumulated raw doré receipts into a finished, investment-grade VaultBatch.
 * Enforces the physical refinery boundary (London Good Delivery >= 99.50% purity).
 */
export async function bridgeDoréToRefinedVault(input: BridgeDoreInput) {
  if (input.refinedFineness < MIN_REFINED_FINENESS) {
    throw new Error(
      `Refined purity ${(input.refinedFineness * 100).toFixed(2)}% is below the required 99.50% investment-grade standard`
    );
  }

  const uniqueReceiptNumbers = Array.from(new Set(input.receiptNumbers));
  if (uniqueReceiptNumbers.length === 0) {
    throw new Error("No receipt numbers provided for refining bridge");
  }

  const refinedFineGrams = Number((input.refinedGrossGrams * input.refinedFineness).toFixed(4));
  let totalRawFineGrams = 0;

  // Execute Bridge Transaction atomically
  const batch = await prisma.$transaction(async (tx) => {
    const receipts = await tx.oreIntakeReceipt.findMany({
      where: { receiptNumber: { in: uniqueReceiptNumbers } },
    });

    if (receipts.length !== uniqueReceiptNumbers.length) {
      throw new Error("One or more ore intake receipts could not be found");
    }

    for (const r of receipts) {
      if (r.status !== "PURCHASED") {
        throw new Error(`Receipt '${r.receiptNumber}' is already in state '${r.status}'`);
      }
    }

    totalRawFineGrams = receipts.reduce((sum, r) => sum + r.fineGoldGrams, 0);

    // Recovery variance check (refined gold should closely match raw doré fine gold content)
    const varianceRatio = refinedFineGrams / totalRawFineGrams;
    if (varianceRatio < 0.95 || varianceRatio > 1.05) {
      throw new Error(
        `Smelting recovery variance out of bounds (${(varianceRatio * 100).toFixed(1)}%). Expected between 95% and 105%.`
      );
    }

    // 1. Mark raw ore receipts as settled into the refined batch
    await tx.oreIntakeReceipt.updateMany({
      where: { receiptNumber: { in: uniqueReceiptNumbers } },
      data: {
        status: "REFINED_SETTLED",
        transferredBatchNumber: input.targetBatchNumber,
      },
    });

    // 2. Ensure gold commodity reserve exists
    const reserve = await tx.commodityReserve.upsert({
      where: { commodityType_symbol: { commodityType: "GOLD", symbol: "Au" } },
      create: { commodityType: "GOLD", symbol: "Au" },
      update: {},
    });

    // 3. Create the investment-grade VaultBatch
    return tx.vaultBatch.create({
      data: {
        batchNumber: input.targetBatchNumber,
        reserveId: reserve.id,
        vaultId: input.vaultId,
        custodianName: input.custodianName,
        locationCity: input.locationCity,
        locationCountry: input.locationCountry.toUpperCase(),
        barSerials: input.barSerials,
        grossWeightGrams: input.refinedGrossGrams,
        fineness: input.refinedFineness,
        fineWeightGrams: refinedFineGrams,
        status: "AUDITED",
        auditedAt: new Date(),
      },
    });
  });

  // 4. Update the live Proof-of-Reserves Merkle tree with the new refined lot
  const livePoR = await generateLivePoR("GOLD");

  return {
    vaultBatch: batch,
    receiptsRefinedCount: uniqueReceiptNumbers.length,
    totalRawFineGrams,
    refinedFineGrams,
    newReserveMerkleRoot: livePoR.reserve.merkleRoot,
  };
}

/**
 * Lists all active buying stations across Mali, Burkina Faso, and Niger.
 */
export async function listBuyingStations() {
  return prisma.artisanalBuyingStation.findMany({
    orderBy: { stationCode: "asc" },
  });
}

/**
 * Retrieves aggregate artisanal mining metrics.
 */
export async function getArtisanalMetrics() {
  const [stations, receipts] = await Promise.all([
    prisma.artisanalBuyingStation.findMany(),
    prisma.oreIntakeReceipt.findMany({
      select: { grossWeightGrams: true, fineGoldGrams: true, payoutAngel: true, status: true },
    }),
  ]);

  const totalGrossGrams = receipts.reduce((sum, r) => sum + r.grossWeightGrams, 0);
  const totalFineGrams = receipts.reduce((sum, r) => sum + r.fineGoldGrams, 0);
  const totalAngelPaid = receipts.reduce((sum, r) => sum + r.payoutAngel, 0);
  const refinedCount = receipts.filter((r) => r.status === "REFINED_SETTLED").length;

  return {
    totalBuyingStations: stations.length,
    activeStations: stations.filter((s) => s.activeStatus === "ACTIVE").length,
    totalIntakeReceipts: receipts.length,
    totalGrossGramsFormalized: Number(totalGrossGrams.toFixed(2)),
    totalFineGramsFormalized: Number(totalFineGrams.toFixed(2)),
    totalAngelPaidToMiners: totalAngelPaid,
    receiptsRefinedToBullion: refinedCount,
    receiptsInTransit: receipts.length - refinedCount,
  };
}
