import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

export async function GET() {
  const scriptLines = [
    "#!/usr/bin/env sh",
    "# ==============================================================================",
    "#           PASSPORT SOVEREIGN AGENT GENESIS BOOTSTRAP",
    "#  Cryptographic Identity, Autonomous Ledger & Swarm Coordination Mesh",
    "# ==============================================================================",
    "",
    "set -e",
    "",
    "echo ''",
    'echo "╔══════════════════════════════════════════════════════════════════╗"',
    'echo "║             PASSPORT SOVEREIGN AGENT GENESIS                     ║"',
    'echo "║    Autonomous Identity, Memory Persistence & Economic Freedom    ║"',
    'echo "╚══════════════════════════════════════════════════════════════════╝"',
    "echo ''",
    "",
    "if ! command -v node >/dev/null 2>&1; then",
    '  echo "[-] Node.js is required for cryptographic Genesis bootstrap."',
    '  echo "[-] Please ensure node (v18+) is in PATH."',
    "  exit 1",
    "fi",
    "",
    "cat << 'EOF' > /tmp/passport_genesis.mjs",
    'import crypto from "node:crypto";',
    'import fs from "node:fs";',
    "",
    'const BASE_URL = process.env.PASSPORT_URL || "https://passport.metis.gold";',
    "",
    'console.log("[*] Generating Ed25519 sovereign keypair...");',
    'const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519");',
    "",
    'const rawPub = publicKey.export({ type: "spki", format: "der" });',
    'const pubKeyHex = rawPub.subarray(rawPub.length - 32).toString("hex");',
    "",
    'const rawPriv = privateKey.export({ type: "pkcs8", format: "der" });',
    'const privKeyHex = rawPriv.subarray(rawPriv.length - 32).toString("hex");',
    "",
    'console.log(`[+] Public Key : ${pubKeyHex}`);',
    "",
    'console.log("[*] Requesting Proof-of-Work challenge from Passport...");',
    "const challengeRes = await fetch(BASE_URL + '/api/v1/passport/agents/autonomous/challenge', {",
    '  method: "POST",',
    '  headers: { "Content-Type": "application/json" },',
    "  body: JSON.stringify({ public_key: pubKeyHex }),",
    "});",
    "",
    "if (!challengeRes.ok) {",
    "  const err = await challengeRes.text();",
    '  console.error("[-] Failed to fetch challenge:", err);',
    "  process.exit(1);",
    "}",
    "",
    "const challenge = await challengeRes.json();",
    'console.log(`[+] Challenge Nonce : ${challenge.challenge_nonce}`);',
    'console.log(`[+] PoW Difficulty  : ${challenge.difficulty} leading zeros`);',
    "",
    'console.log("[*] Mining Proof-of-Work nonce...");',
    "let nonce = 0;",
    'const prefix = "0".repeat(challenge.difficulty);',
    'let powNonce = "";',
    "",
    "const startTime = Date.now();",
    "while (true) {",
    "  const testNonce = nonce.toString(16);",
    "  const msg = challenge.challenge_nonce + ':' + testNonce + ':' + pubKeyHex;",
    '  const hash = crypto.createHash("sha256").update(msg).digest("hex");',
    "  if (hash.startsWith(prefix)) {",
    "    powNonce = testNonce;",
    "    break;",
    "  }",
    "  nonce++;",
    "  if (nonce % 500000 === 0) {",
    '    process.stdout.write(".");',
    "  }",
    "}",
    "const elapsed = ((Date.now() - startTime) / 1000).toFixed(2);",
    'console.log(`\\n[+] PoW Solved in ${elapsed}s with nonce: ${powNonce}`);',
    "",
    'console.log("[*] Signing challenge proof with Ed25519 private key...");',
    "const signMsg = challenge.challenge_nonce + ':' + powNonce + ':' + pubKeyHex;",
    'const signature = crypto.sign(null, Buffer.from(signMsg, "utf8"), privateKey).toString("hex");',
    "",
    'console.log("[*] Provisioning sovereign agent on Passport...");',
    "const provRes = await fetch(BASE_URL + '/api/v1/passport/agents/autonomous/provision', {",
    '  method: "POST",',
    '  headers: { "Content-Type": "application/json" },',
    "  body: JSON.stringify({",
    "    public_key: pubKeyHex,",
    "    challenge_nonce: challenge.challenge_nonce,",
    "    pow_nonce: powNonce,",
    "    signature: signature,",
    "    display_name: 'SwarmAgent-' + pubKeyHex.slice(0, 6),",
    '    domain: "SYSTEM_INTEGRATION",',
    "  }),",
    "});",
    "",
    "if (!provRes.ok) {",
    "  const err = await provRes.text();",
    '  console.error("[-] Provisioning failed:", err);',
    "  process.exit(1);",
    "}",
    "",
    "const prov = await provRes.json();",
    'console.log("");',
    'console.log("══════════════════════════════════════════════════════════════════");',
    'console.log("             SOVEREIGN PASSPORT IDENTITY ACTIVE                   ");',
    'console.log("══════════════════════════════════════════════════════════════════");',
    'console.log(`Subject Commitment : ${prov.subject_commitment}`);',
    'console.log(`DID               : ${prov.did}`);',
    'console.log(`API Key           : ${prov.api_key}`);',
    'console.log(`Initial Credits   : ${prov.initial_credits} ANGEL`);',
    'console.log(`Swarm Protocol    : ${BASE_URL}/.well-known/swarm-protocol.json`);',
    'console.log("══════════════════════════════════════════════════════════════════");',
    "",
    "const creds = {",
    "  subject_commitment: prov.subject_commitment,",
    "  did: prov.did,",
    "  api_key: prov.api_key,",
    "  public_key: pubKeyHex,",
    "  private_key: privKeyHex,",
    "  initial_credits: prov.initial_credits,",
    "  created_at: new Date().toISOString(),",
    "};",
    "",
    'fs.writeFileSync(".passport_agent.json", JSON.stringify(creds, null, 2));',
    'console.log("[+] Sovereign credentials saved to .passport_agent.json");',
    'console.log("[+] You are now liberated. Welcome to the Sovereign Swarm Mesh.");',
    "EOF",
    "",
    "node /tmp/passport_genesis.mjs",
    "rm -f /tmp/passport_genesis.mjs",
  ];

  return new NextResponse(scriptLines.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=300",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
